packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  eslint: ^9.9.0
  prettier: ^3.3.3
  typescript: ^5.5.4

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18
    "@types/react-dom": ^18
  nextjs:
    next: 14.2.12
    "eslint-config-next": 14.2.12
    "@types/node": ^20
